### ISSUE TITLE
Last commit solves half the discussion question

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/react-hooks-dq-extracting-components#2]
### Canvas Link

https://learning.flatironschool.com/courses/4993/discussion_topics/13070

### Concern

It seems that the most recent commit: 75164a90403c59f2a55809fbf3a0d323b68be663
solves half of the discussion question problem. 

### Suggested Changes

Revert the main branch to 84cd25669c43c9f61145b46179cf1ff69a8a25ad

**Comment by lizbur10** [comment]
Thanks @betalantz !
